### ISSUE TITLE
Failure/hang in compile on RHEL7 PPCLE and x86

### ISSUE THREAD

**Issue by jdekonin** [ibmruntimes/openj9-openjdk-jdk8#7]
I am attempting to compile on a rhel7.2 ppcle machine and getting this error.

```
OpenJ9 compile complete
Creating support/modules_libs/java.base/server/libjvm.so from J9 sources
Creating support/modules_libs/java.base/libjsig.so from J9 sources
(cd /tmp/bld_371745/openjdk/closed && /usr/bin/gmake -s VERBOSE="-s" LOG_LEVEL="warn" -I /tmp/bld_371745/openjdk/make/common -f OpenJ9.gmk SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk stage_openj9_build_jdk)
Setting /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/jdk/lib/classlib.properties
## Starting corba
Compiling 6 files for BUILD_LOGUTIL
/tmp/bld_371745/openjdk/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:35: error: cannot access Object
public class IndentingPrintWriter extends PrintWriter {
       ^
  class file for java.lang.Object not found
/tmp/bld_371745/openjdk/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:38: error: cannot find symbol
    private String indentString = "" ;
            ^
  symbol:   class String
  location: class IndentingPrintWriter
```

The SDK I am using is: 
```
Java(TM) SE Runtime Environment (build pxl6470_27sr5-20171115_03(SR5))
IBM J9 VM (build 2.7, JRE 1.7.0 Linux ppc64le-64 Compressed References 20171111_369890 (JIT enabled, AOT enabled)
J9VM - R27_jvm.27_20171111_1528_B369890
JIT  - tr.r13.java_20171111_369890
GC   - R27_jvm.27_20171111_1528_B369890_CMPRSS
J9CL - 20171111_369890)
JCL - 20171109_01 based on Oracle jdk7u161-b13
```

It appears that OpenJ9 compilation (native only??) is complete; I don't see any Object or String class within the $openjdk/build/ directory.  When I use openjdk7 (b95) I don't have this issue, but 'make images' hangs at 'Creating images/lib/jsse.jar'.  Performing top shows that gmake is consuming 100% cpu, I've been killing it after an hour.

Currently I am attempting with openjdk b151 to see if I get any further.

**Comment by pshipton** [comment]
I wonder if the vm.jar (which contains Object) used by IBM builds is causing the problem. You could try putting the contents of vm.jar into the rt.jar and see if that resolves the problem.

**Comment by jdekonin** [comment]
That doesn't work either @pshipton. I also tested updating make as well as using openjdk8(b151) as a bootjdk with no positive outcomes.

This is what is running at the time of a hang:
```23041 20642 /bin/sh -c (cd /tmp/bld_371745/openjdk/jdk/make && /usr/bin/bash /tmp/bld_371745/openjdk/common/bin/logger.sh /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log /usr/bin/gmake -s VERBOSE="-s" LOG_LEVEL="warn" -I /tmp/bld_371745/openjdk/make/common "SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk" -j7 -f BuildJdk.gmk images)
20642 20643 /bin/sh -c (cd /tmp/bld_371745/openjdk/jdk/make && /usr/bin/bash /tmp/bld_371745/openjdk/common/bin/logger.sh /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log /usr/bin/gmake -s VERBOSE="-s" LOG_LEVEL="warn" -I /tmp/bld_371745/openjdk/make/common "SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk" -j7 -f BuildJdk.gmk images)
20643 20644 /usr/bin/bash /tmp/bld_371745/openjdk/common/bin/logger.sh /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log /usr/bin/gmake -s VERBOSE=-s LOG_LEVEL=warn -I /tmp/bld_371745/openjdk/make/common SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk -j7 -f BuildJdk.gmk images
20644 20646 /usr/bin/bash /tmp/bld_371745/openjdk/common/bin/logger.sh /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log /usr/bin/gmake -s VERBOSE=-s LOG_LEVEL=warn -I /tmp/bld_371745/openjdk/make/common SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk -j7 -f BuildJdk.gmk images
20644 20647 tee -a /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log
20646 20648 /usr/bin/bash /tmp/bld_371745/openjdk/common/bin/logger.sh /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log /usr/bin/gmake -s VERBOSE=-s LOG_LEVEL=warn -I /tmp/bld_371745/openjdk/make/common SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk -j7 -f BuildJdk.gmk images
20646 20649 tee -a /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/build.log
20648 20650 /usr/bin/gmake -s VERBOSE=-s LOG_LEVEL=warn -I /tmp/bld_371745/openjdk/make/common SPEC=/tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/spec.gmk -j7 -f BuildJdk.gmk images
20650 20653 /usr/bin/gmake -s VERBOSE=-s LOG_LEVEL=warn -I /tmp/bld_371745/openjdk/make/common PROFILE= -f CreateJars.gmk
20653 20919 [sh] <defunct>
20653 20920 [sh] <defunct>
20653 20931 [mkdir] <defunct>
  556 20941 sshd: root@pts/1
20941 20943 -bash
20943 21147 ps -eo %P %p %a
11234 23041 make images
```

Top reports 20643 as the pid that has 100% CPU.

Adding debug logging and I believe this is where its hanging.
```
SetupZipArchive(BUILD_SEC_BIN_ZIP) 
 [2] SRC := /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/jdk 
 [3] INCLUDES := classes/javax/net classes/javax/security/cert classes/com/sun/net/ssl classes/com/sun/security/cert classes/sun/net/www/protocol/https classes/sun/security/pkcs12 classes/sun/security/ssl classes/sun/security/krb5 classes/sun/security/krb5/internal classes/sun/security/krb5/internal/ccache classes/sun/security/krb5/internal/crypto classes/sun/security/krb5/internal/ktab classes/sun/security/krb5/internal/rcache classes/sun/security/krb5/internal/util 
 [4] INCLUDE_FILES := classes/sun/security/jgss/spi/GSSContextSpi.class 
 [5] EXCLUDES := classes/sun/security/krb5/internal/tools 
 [6] ZIP := /tmp/bld_371745/openjdk/build/linux-ppc64-normal-server-release/images/sec-bin.zip      
```

**Comment by andrew-m-leonard** [comment]
This is a known issue when trying to use IBM boot jvm to build, due to corba and IBM orb differences I think. Adopt discovered this originally, hence they use openjdk7 to build as per the docker image.

**Comment by jdekonin** [comment]
Can you please point me at a functioning docker image for rhel7 or is there an existing build on adoptopenjdk that I am missing?

**Comment by jdekonin** [comment]
I found an openjdk8 build on adopt that builds on fedora24.  I used those same steps to successfully build on my rhel7 machine using the same configure options as I used with the openj9 variant.

This would seem to imply that there is something amiss within the openj9-openjdk-jdk8 add-ons with make target dependencies.

**Comment by sxa555** [comment]
@jdekonin Can you verify whether upgrading to make 4.1 resolves this problem for you?

**Comment by cwesMills** [comment]
I was able to build jdk8 on ppc64le cent7, when I updated make 3.8 to make 4.1.

**Comment by jdekonin** [comment]
Awesome.  Thanks for verifying this @cwesMills
