### PR TITLE
Use recur_wildcard instead of RecursiveWildcard

### PR DESCRIPTION
**Pull request by JasonFengJ9**
This fixes compilation errors such as `job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/373/consoleFull`.

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
Jenkins compile all jdk8

**Comment by pshipton** [comment]
The original worked on an older version of cygwin (2.10, with older tools?), but not a newer version (3.1.7).

File: closed/OpenJ9.gmk [hunk 1]
```diff
@@ -475,7 +475,7 @@ endef # RunJPP
 IncludeIfUnsure := -includeIfUnsure -noWarnIncludeIf
 
 $(J9JCL_SOURCES_DONEFILE) : \
-		$(foreach dir, $(JppSourceDirs), $(call RecursiveWildcard,$(dir),*.java))
+		$(foreach dir, $(JppSourceDirs), $(call recur_wildcard,$(dir),*.java))
```
Comment (keithc-ca) [inline closed/OpenJ9.gmk:478]: I suggest a better change is to rename the macro `recur_wildcard` (on line 436) to `RecursiveWildcard` for consistency with other jdk versions (probably from which this was copied).

**Comment by pshipton** [comment]
On second review we're not sure if this fixes the problem or not. I'm not sure if there is a good way to try any fix in advance of merging, there are no personal builds for the Adoptium pipelines where it fails. @AdamBrousseau ?

File: closed/OpenJ9.gmk (hunk 1 above)
Comment (JasonFengJ9) [reply closed/OpenJ9.gmk]: Renamed `recur_wildcard` to `RecursiveWildcard`.

**Comment by keithc-ca** [comment]
The most recent change should not invalidate the previous build success: https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDK8/39/.

**Comment by AdamBrousseau** [comment]
We can launch a build with custom extensions repo/branch.
Like we do for CE
          buildArgs : "--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk"

**Comment by keithc-ca** [comment]
See https://github.com/adoptium/temurin-build/pull/2944.
